//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercePrototype.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommercePrototype.Tests.SampleData", typeof(SampleData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aenean.eget.metus@Sedmalesuadaaugue.com;non.dapibus.rutrum@tinciduntvehicularisus.com;ac.turpis@risusvarius.net;non.cursus@magna.org;aliquet.diam@acmattisornare.net;Aliquam@idsapienCras.net;magna.tellus.faucibus@dolorelitpellentesque.edu;non@eumetus.com;massa.Quisque.porttitor@pede.net;ac.nulla.In@CurabiturmassaVestibulum.com;tincidunt@Sedidrisus.com;neque.In@etpede.edu;congue@Vivamusnonlorem.com;lobortis.risus.In@hymenaeosMauris.edu;elit.Aliquam@scelerisquescelerisque.com;diam@ut.ca;fermentum@Integeraliqua [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JML00JKP1ZP;JCH12POJ3GS;WJQ11GGN0PZ;MQZ80OZA1IC;MOK01TLJ4IS;BNX37LIJ4UA;KPB95BDX1QL;OSO31YTM6VZ;ODT94CKG1UW;ETK29IKN7ZG;IHK20WXW8MZ;PML68SUQ5YK;YFI26WBP0KX;MQY35VFB8UN;HMJ92ANG4ML;TUB58RRF5DW;NML36MEM9MZ;ILH39OTM9MG;BCB77HHW1VJ;PEB03OAV5JH;VSH34TJZ9LB;BEV34SMG0BL;DCV61QGN9CG;FMT98SYH7ZL;PIW37DJW5NZ;KFC04QAN8FA;PEW31DCC5SK;LAF63BFX0QC;DRN76BQX0FB;YOE06HQJ6CK;XSU99RAN7EF;HYW35TLU8JJ;AKA20JZD7WV;OWT28GZB4GZ;IQO10JYK7YV;TFW11AXB8LX;QRU86VJX8RN;KUO77ZNR7GW;RKB72CPT0FK;UCB64YMD4XX;ASQ92HUM1LW;GEE37YJY3EA;JVM33PTF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $5 Virtual Gift Card;$25 Virtual Gift Card;$50 Physical Gift Card;$100 Physical Gift Card;50&apos;s Rockabilly Polka Dot Top JR Plus Size;Acer Aspire One 8.9&quot; Mini-Notebook Case - (Black);adidas Women&apos;s Supernova CSH 7 Running Shoe;Adobe Photoshop Elements 7;APC Back-UPS RS 800VA - UPS - 800 VA - UPS battery - lead acid ( BR800BLK );Arrow Men&apos;s Wrinkle Free Pinpoint Solid Long Sleeve;ASUS Eee PC 1000HA 10-Inch Netbook;ASUS Eee PC 900HA 8.9-Inch Netbook Black;Best Grilling Recipes;Black &amp; White Diamond Heart;Blac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductNames {
            get {
                return ResourceManager.GetString("ProductNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByronRay;FrancisBowen;IvanRodriguez;LindaGamble;DanielleBarnett;SageBoyer;AmeliaVelazquez;LysandraCarver;MaconWelch;BorisGarcia;CamillaMeadows;KevinPeters;PatienceRodgers;CarsonBurris;QuynnGarcia;AlfredaValdez;AuroraGray;AaronLe;CairoMckinney;ShayHanson;MarikoNorton;JenetteOneal;LionelBoyd;SebastianDavenport;AmethystWeaver;KieranCortez;KylynnBradford;UrielFranco;StuartBoyd;ImeldaMoses;HunterHumphrey;KylynnKennedy;RubyMarshall;AladdinWhitfield;CarsonSteele;GeorgeSalas;KiayadaSchmidt;JordanCarson;TravisGay;Ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Usernames {
            get {
                return ResourceManager.GetString("Usernames", resourceCulture);
            }
        }
    }
}
